# ---------------------------------------------------------------
# General config
# predator_pc@2019
# all tech stack
# ---------------------------------------------------------------

version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - ${HTTP_DEV_SERVER_PORT}:80
        volumes:
            - ./app:/var/www/app
            - ./config/host.conf:/etc/nginx/conf.d/default.conf
            - ./log:/var/log/nginx
        networks:
            - app-network
    php:
        build: ./config/php
        volumes:
            - ./app:/var/www/app
        networks:
            - app-network
    rabbitmq:
        image: rabbitmq:3.6.1-management
        environment:
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
            RABBITMQ_NODENAME: leadstorage@rabbitmq
        ports:
            - ${RABBITMQ_MANAGEMENT_PORT}:15672
            - ${RABBITMQ_EXCHANGE_PORT}:5672
        volumes:
            - ./rabbitmq_data:/var/lib/rabbitmq
        networks:
            - app-network
    mongodb:
        image: mongo
        volumes:
            - ./data/db/mongo:/data/db
        ports:
            - ${MONGO_DEV_SERVER_PORT}:27017
        command: --storageEngine wiredTiger
        networks:
            - app-network
#
# Additional stuff and databases
#
# Redis
#   redis:
#   image: redis:4.0-alpine
##      command:
##          - 'redis-server'
##          - '--loglevel ${REDIS_LOGLEVEL:-warning}'
##          - '--databases 2'
##          - '--maxmemory ${REDIS_MAXMEM:-50mb}'
##          - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
##          - '--requirepass ${REDIS_PASS}'
#   volumes:
#       - ./redis:/data
#   ports:
#       - ${REDIS_DEV_PORT}:6379
#    networks:
#       - app-network
#
# Yandex ClickHouse
#    clickhouse:
#        image: yandex/clickhouse-server
#        volumes:
#          - ./clickhouse-data:/var/lib/clickhouse
#        ports:
#            - ${CLICKHOUSR_DEV_PORT}:8123
#    networks:
#       - app-network
#    clickouseclient:
#        image: yandex/clickhouse-client
#    networks:
#       - app-network
#
# MySQL
#    mysql:
#        image: mysql:5.6
#        ports:
#            - ${MYSQL_DEV_SERVER_PORT}:3306
#        environment:
#              MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#              MYSQL_DATABASE: ${MYSQL_DATABASE}
#              MYSQL_USER: ${MYSQL_USER}
#              MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#        volumes:
#            - ./mysql:/var/lib/mysql
#        networks:
#            - app-network
#
# Tools for MySQL
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        environment:
#            PMA_HOST: "mysql"
#        ports:
#            - ${MYADMIN_DEV_SERVER_PORT}:80
#        networks:
#            - app-network
#
# Portainer to organize your docker from UI
#    portainer:
#        image: portainer/portainer
#        ports:
#            - ${PORTAINER_DEV_PORT}:9000
#        volumes:
#           - /var/run/docker.sock:/var/run/docker.sock
#           - /opt/portainer/data:/data

networks:
    app-network:
        driver: bridge