FROM yandex/clickhouse-server

MAINTAINER Michael S. Merzlyakov <michael@merzlyakov.pro>

RUN apt-get update -y
RUN apt-get install -y git mc curl python3.6 python3-pip
RUN pip3 install altinity-datasets